# Generated by Django 3.2.20 on 2023-11-27 03:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('type', models.CharField(default='post', max_length=1024)),
                ('title', models.CharField(max_length=512)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=1024)),
                ('origin', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('contentType', models.CharField(max_length=1024)),
                ('content', models.TextField()),
                ('categories', models.JSONField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('comments', models.CharField(blank=True, max_length=1024)),
                ('published', models.DateTimeField(default=datetime.datetime.now)),
                ('visibility', models.CharField(choices=[('FRIENDS', 'Friends'), ('PUBLIC', 'Public')], default='PUBLIC', max_length=10)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
