# Generated by Django 3.2.20 on 2023-11-27 03:03

from django.db import migrations, models
import django.db.models.deletion
import user.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=1024, unique=True)),
                ('password', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=1024)),
                ('host', models.CharField(max_length=1024)),
                ('is_active', models.BooleanField(default=False)),
                ('displayName', models.CharField(max_length=1024)),
                ('github', models.CharField(max_length=1024)),
                ('profileImage', models.CharField(blank=True, max_length=1024)),
                ('biography', models.TextField(default='I am too lazy to leave a bio.....')),
                ('type', models.CharField(choices=[('AUTHOR', 'Author'), ('SERVERADMIN', 'ServerAdmin')], default='AUTHOR', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='user.user')),
                ('Admin_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('type', models.CharField(default='like', max_length=1024)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=1024)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.JSONField(default=user.models.Inbox.default_items)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='inbox',
            constraint=models.UniqueConstraint(fields=('author',), name='unique_author_inbox'),
        ),
    ]
